# nginx proxy address - http://172.17.0.1:60190

name: ghost
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghost:latest
    container_name: ghost-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      NODE_ENV: production
      url: https://${BASE_HOST_NAME:-$HOSTNAME}
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__port: 3306
      database__connection__user: ${DB_USER_NAME:-ghost}
      database__connection__database: ${DB_CREATE_DATABASE_NAME:-ghost}
      database__connection__password: ${DB_USER_PASS:-changeme_db_password}
      mail__transport: SMTP
      mail__options__host: ${EMAIL_SERVER_HOST:-172.17.0.1}
      mail__options__port: ${EMAIL_SERVER_PORT:-587}
      mail__options__auth__user: ${EMAIL_SERVER_LOGIN_NAME:-}
      mail__options__auth__pass: ${EMAIL_SERVER_LOGIN_PASS:-}
      mail__from: ${EMAIL_SERVER_MAIL_FROM:-noreply@example.com}
      CONTAINER_NAME: ghost-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:60190:2368'
    volumes:
      - './volumes/data/ghost:/var/lib/ghost/content'
    depends_on:
      - db
    networks:
      - ghost
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://ghost-app:2368'
      - 'cloudflare.hostname=ghost.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.ghost-app.entrypoints=http'
      - 'traefik.http.routers.ghost-app-secure.tls=true'
      - 'traefik.http.routers.ghost-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.ghost-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.ghost-app.middlewares=ghost-app-https-redirect'
      - 'traefik.http.routers.ghost-app-secure.entrypoints=https'
      - 'traefik.http.routers.ghost-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.ghost-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.ghost-app-secure.service=ghost-app'
      - 'traefik.http.services.ghost-app.loadbalancer.server.port=2368'

  db:
    image: mysql:latest
    container_name: ghost-db
    hostname: ghost-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASS:-changeme_admin_password}
      MYSQL_DATABASE: ${DB_CREATE_DATABASE_NAME:-ghost}
      MYSQL_USER: ${DB_USER_NAME:-ghost}
      MYSQL_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      CONTAINER_NAME: ghost-db
    volumes:
      - './volumes/data/db/mysql/ghost:/var/lib/mysql'
    networks:
      - ghost

networks:
  ghost:
    name: ghost
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
