#
name: ghost
services:
  ghost:
    image: ghost:latest
    restart: always
    pull_policy: always 
    environment:
      NODE_ENV: production
      url: http://${BASE_HOST_NAME:-$HOSTNAME}
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    ports:
      - '172.17.0.1:60190:2368'
    volumes:
      - ghost:/var/lib/ghost/content
    networks:
      - ghost

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql
    networks:
      - ghost

networks:
  ghost:
    name: ghost
    external: false
    
